import { CryptoCurrency, RiskLevel, ThreatType, Transaction } from '../types/crypto';
import { apiFetch } from './apiClient';
export interface TransactionFilterOptions { searchQuery?:string; riskLevel?:RiskLevel|'all'; currency?:CryptoCurrency|'all'; threatType?:ThreatType|'all'; status?:string; sortBy?:'timestamp'|'amount'|'riskScore'|'aiConfidence'; sortOrder?:'asc'|'desc'; }
class TransactionService {
 private transactions:Transaction[]=[];
 async load(options:TransactionFilterOptions={}):Promise<Transaction[]>{const q=new URLSearchParams();if(options.searchQuery)q.set('search',options.searchQuery);if(options.riskLevel&&options.riskLevel!=='all')q.set('riskLevel',options.riskLevel);if(options.currency&&options.currency!=='all')q.set('currency',options.currency);if(options.threatType&&options.threatType!=='all')q.set('threatType',options.threatType);if(options.status&&options.status!=='all')q.set('status',options.status);if(options.sortBy)q.set('sortBy',options.sortBy);if(options.sortOrder)q.set('sortOrder',options.sortOrder);const r=await apiFetch<{transactions:Transaction[]}>(`/transactions?${q}`);this.transactions=r.transactions;return this.transactions;}
 getAll(){return [...this.transactions];}
 getById(id:string){return this.transactions.find(t=>t.id===id||t.hash.toLowerCase()===id.toLowerCase());}
 filter(options:TransactionFilterOptions){let r=[...this.transactions];const q=options.searchQuery?.trim().toLowerCase();if(q)r=r.filter(t=>[t.id,t.hash,t.senderAddress,t.receiverAddress,t.threatType].some(v=>v.toLowerCase().includes(q)));if(options.riskLevel&&options.riskLevel!=='all')r=r.filter(t=>t.riskLevel===options.riskLevel);if(options.currency&&options.currency!=='all')r=r.filter(t=>t.currency===options.currency);if(options.threatType&&options.threatType!=='all')r=r.filter(t=>t.threatType===options.threatType);if(options.status&&options.status!=='all')r=r.filter(t=>t.status.toLowerCase()===options.status!.toLowerCase());const field=options.sortBy||'timestamp';const order=options.sortOrder||'desc';return r.sort((a,b)=>{const va=field==='timestamp'?Date.parse(a.timestamp):Number(a[field]);const vb=field==='timestamp'?Date.parse(b.timestamp):Number(b[field]);return (va<vb?-1:va>vb?1:0)*(order==='asc'?1:-1);});}
 async updateStatus(id:string,status:Transaction['status']){const r=await apiFetch<{transaction:Transaction}>(`/transactions/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});this.transactions=this.transactions.map(t=>t.id===id?r.transaction:t);return r.transaction;}
}
export const transactionService=new TransactionService();
