import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth.js';
import { query } from '../db.js';
const router=Router();router.use(requireAuth);
const schema=z.object({name:z.string().trim().min(2),email:z.string().email(),department:z.string().trim().min(2),riskSensitivity:z.enum(['high','medium','strict']),twoFactorEnabled:z.boolean(),autoBlockHighRisk:z.boolean(),webhookUrl:z.string().refine(v=>!v||/^https?:\/\//.test(v),'Webhook URL must be HTTP/HTTPS')});
router.get('/',async(req,res,next)=>{try{const r=await query('SELECT * FROM soc_preferences WHERE user_id=$1',[req.user!.id]);if(!r.rowCount)return res.json({preferences:null});const x=r.rows[0];res.json({preferences:{name:x.name,email:x.email,department:x.department,riskSensitivity:x.risk_sensitivity,twoFactorEnabled:x.two_factor_enabled,autoBlockHighRisk:x.auto_block_high_risk,webhookUrl:x.webhook_url,lastUpdated:new Date(x.updated_at).toISOString()}});}catch(e){next(e);}});
router.put('/',async(req,res,next)=>{try{const x=schema.parse(req.body);const r=await query(`INSERT INTO soc_preferences(user_id,name,email,department,risk_sensitivity,two_factor_enabled,auto_block_high_risk,webhook_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id) DO UPDATE SET name=EXCLUDED.name,email=EXCLUDED.email,department=EXCLUDED.department,risk_sensitivity=EXCLUDED.risk_sensitivity,two_factor_enabled=EXCLUDED.two_factor_enabled,auto_block_high_risk=EXCLUDED.auto_block_high_risk,webhook_url=EXCLUDED.webhook_url,updated_at=NOW() RETURNING *`,[req.user!.id,x.name,x.email,x.department,x.riskSensitivity,x.twoFactorEnabled,x.autoBlockHighRisk,x.webhookUrl]);const y=r.rows[0];res.json({preferences:{name:y.name,email:y.email,department:y.department,riskSensitivity:y.risk_sensitivity,twoFactorEnabled:y.two_factor_enabled,autoBlockHighRisk:y.auto_block_high_risk,webhookUrl:y.webhook_url,lastUpdated:new Date(y.updated_at).toISOString()}});}catch(e){next(e);}});
export default router;
