import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';
import { txRow } from '../utils/serialize.js';

const router=Router(); router.use(requireAuth);
router.get('/',async(req,res,next)=>{try{const {search,riskLevel,currency,threatType,status,sortBy='timestamp',sortOrder='desc'}=req.query; const where:string[]=[]; const p:any[]=[]; const add=(sql:string,v:any)=>{p.push(v);where.push(sql.replace('$X',`$${p.length}`));}; if(search){add(`(LOWER(id) LIKE LOWER('%' || $X || '%') OR LOWER(hash) LIKE LOWER('%' || $X || '%') OR LOWER(sender_address) LIKE LOWER('%' || $X || '%') OR LOWER(receiver_address) LIKE LOWER('%' || $X || '%') OR LOWER(threat_type) LIKE LOWER('%' || $X || '%'))`,String(search));} if(riskLevel&&riskLevel!=='all')add('risk_level=$X',riskLevel);if(currency&&currency!=='all')add('currency=$X',currency);if(threatType&&threatType!=='all')add('threat_type=$X',threatType);if(status&&status!=='all')add('LOWER(status)=LOWER($X)',status); const allowed:any={timestamp:'timestamp',amount:'amount',riskScore:'risk_score',aiConfidence:'ai_confidence'}; const order=allowed[String(sortBy)]??'timestamp'; const dir=String(sortOrder).toLowerCase()==='asc'?'ASC':'DESC'; const sql=`SELECT * FROM transactions ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY ${order} ${dir}`;const r=await query(sql,p);res.json({transactions:r.rows.map(txRow)});}catch(e){next(e);}});
router.get('/:id',async(req,res,next)=>{try{const r=await query('SELECT * FROM transactions WHERE id=$1 OR LOWER(hash)=LOWER($1)',[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Transaction not found.'});res.json({transaction:txRow(r.rows[0])});}catch(e){next(e);}});
router.patch('/:id/status',async(req,res,next)=>{try{const allowed=['Approved','Flagged','Under Review','Blocked'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid transaction status.'});const r=await query('UPDATE transactions SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.status,req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Transaction not found.'});res.json({transaction:txRow(r.rows[0])});}catch(e){next(e);}});
export default router;
