import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';
import { getRiskLevel } from '../utils/risk.js';
import { txRow } from '../utils/serialize.js';
const router=Router();router.use(requireAuth);
router.get('/:address',async(req,res,next)=>{try{const address=req.params.address;const r=await query(`SELECT * FROM transactions WHERE LOWER(sender_address)=LOWER($1) OR LOWER(receiver_address)=LOWER($1) ORDER BY timestamp DESC LIMIT 500`,[address]);if(!r.rowCount){return res.json({profile:buildEmptyProfile(address)});}const txs=r.rows;const sent=txs.filter(t=>t.sender_address.toLowerCase()===address.toLowerCase());const received=txs.filter(t=>t.receiver_address.toLowerCase()===address.toLowerCase());const scores=txs.map(t=>Number(t.sender_address.toLowerCase()===address.toLowerCase()?t.sender_risk_score:t.receiver_risk_score));const score=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length);const suspicious=txs.filter(t=>Number(t.risk_score)>=55).length;const counterparties=new Map<string,any>();for(const t of txs){const other=t.sender_address.toLowerCase()===address.toLowerCase()?t.receiver_address:t.sender_address;if(!counterparties.has(other))counterparties.set(other,{address:other,label:'Counterparty',type:Number(t.risk_score)>=70?'suspicious_wallet':'clean_user',riskScore:Number(t.risk_score),transactionCount:0,volumeUSD:0,relation:'Transaction Counterparty'});const n=counterparties.get(other);n.transactionCount++;n.volumeUSD+=Number(t.amount_usd);}const profile={address,currency:txs[0].currency,riskScore:score,riskLevel:getRiskLevel(score),transactionCount:txs.length,totalReceivedUSD:received.reduce((s,t)=>s+Number(t.amount_usd),0),totalSentUSD:sent.reduce((s,t)=>s+Number(t.amount_usd),0),firstActive:new Date(Math.min(...txs.map(t=>new Date(t.timestamp).getTime()))).toISOString(),lastActive:new Date(Math.max(...txs.map(t=>new Date(t.timestamp).getTime()))).toISOString(),suspiciousTxCount:suspicious,flaggedCounterpartiesCount:[...counterparties.values()].filter(x=>x.riskScore>=55).length,associatedThreats:[...new Set(txs.filter(t=>t.threat_type!=='Clean Transaction').map(t=>t.threat_type))],tags:suspicious?['High Anomaly Score','Unusual Velocity']:['Standard User'],riskHistory:buildHistory(txs),connectedWallets:[...counterparties.values()].slice(0,12)};res.json({profile});}catch(e){next(e);}});
router.get('/:address/transactions',async(req,res,next)=>{try{const r=await query(`SELECT * FROM transactions WHERE LOWER(sender_address)=LOWER($1) OR LOWER(receiver_address)=LOWER($1) ORDER BY timestamp DESC`,[req.params.address]);res.json({transactions:r.rows.map(txRow)});}catch(e){next(e);}});
function buildHistory(txs:any[]){const days=txs.slice(-4);return days.map((t,i)=>({date:new Date(t.timestamp).toLocaleDateString('en-US',{month:'short',day:'2-digit'}),riskScore:Number(t.risk_score)}));}
function buildEmptyProfile(address:string){return {address,currency:'ETH',riskScore:0,riskLevel:'safe',transactionCount:0,totalReceivedUSD:0,totalSentUSD:0,firstActive:'N/A',lastActive:'N/A',suspiciousTxCount:0,flaggedCounterpartiesCount:0,associatedThreats:[],tags:['No indexed transactions'],riskHistory:[],connectedWallets:[]};}
export default router;
